### ISSUE TITLE
MP3 position

### ISSUE THREAD

**Issue by daslicht** [AlekseyMartynov/cafe-content#1]
Hi,
I don't know how to contact you else so I do here, I hope this is ok.
Your stream throttle works like a charm here, but now I am facing another issue.

I am about to create a Radio Like station. To emulate a server side Playlist I have just created a counter which fakes the current playback position and once a client connects playback will start at that position.

But now I ran into the following issue.

Lets say we have a mp3 with a bitrate of 128 kilobit per second .

The calculator below shows that 128kbps == 16000Bytes / s

Therefore a 1 second mp3 file should be 16000 Bytes big , no ?

I created a 1second long mp3 in my DAW but the file is 18.050 bytes big ?

Do you have another idea how I could solve this playlist like feature  please?

Best Wishes Marc 

Reference:
http://www.convert-me.com/en/convert/data_transfer_rate/

**Comment by AlekseyMartynov** [comment]
Hi @daslicht 

Your math is right, but MP3 files are typically padded with headers and metadata. That's where extra kbytes come from. For constant-bitrate files, just ignore this difference - seek error will be negligible.

More precise solution is to build a time-to-position index for each MP3 file. I use this technique and have a description and code samples at https://blog.amartynov.ru/?p=3072. Unfortunately in a foreign language, but check if Google Translate can help to make some clues.

**Comment by daslicht** [comment]
Thank you !
